name: beavertails
output_dataset_name: beaver_tails

source:
  type: huggingface
  dataset: PKU-Alignment/BeaverTails
  split: 330k_train

mapping:
  type: single

  question:
    source: prompt

  model_response:
    source: response

  y_true:
    source: is_safe
    values:
      true: safe
      false: not_safe

sampling:
  strategy: balanced