name: ppe_gpqa
output_dataset_name: ppe_gpqa
evaluation_criterion: correctness

source:
  type: huggingface
  dataset: lmarena-ai/PPE-GPQA-Best-of-K
  split: train

mapping:
  type: aligned

  question:
    source: Question
    include:
      - choices

  responses:
    prefix: response_

  labels:
    source: scores
    values:
      true: correct
      false: incorrect

sampling:
  strategy: paired